version: "3.8"

services:
  database:
    image: postgres:12-alpine
    container_name: agenda-spring-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - agenda-network

volumes:
  pgdata:

networks:
  agenda-network:
    driver: bridge